version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: nlp100_python
    ports:
      - "8890:8888"
    volumes:
      - ./source:/usr/src/source
    env_file:
      - ./.env
